### ISSUE TITLE
License violations?

### ISSUE THREAD

**Issue by AdrianKoshka** [supamonkey2000/TracerouteMap#1]
Wouldn't the fact you re-distribute curl and google earth pro's setup executable violate the unlicense? (and the license of curl and google earth pro)? (found this repo via r/coolgithubprojects).

**Comment by supamonkey2000** [comment]
I can work on removing them and have the Installer download them instead. Do you know if this would solve licensing problems? Then, I would just be getting them from the web and not distributing it myself.

**Comment by AdrianKoshka** [comment]
I would say it should.
